import os
import threading

LONG_TERM_FILE = "long_term_memory.md"


def initialize_long_term():
    if not os.path.exists(LONG_TERM_FILE):
        default_content = """# Long-Term User & Caretaker Profile

### General Info
- Caretaker managing a neurodivergent care recipient.

### Sensory & Behavioral Triggers
- None logged yet.

### Calming Strategies & Routines
- None logged yet."""

        with open(LONG_TERM_FILE, "w", encoding="utf-8") as f:
            f.write(default_content)


def read_long_term():
    initialize_long_term()

    with open(LONG_TERM_FILE, "r", encoding="utf-8") as f:
        return f.read()


def write_long_term(content):
    with open(LONG_TERM_FILE, "w", encoding="utf-8") as f:
        f.write(content)


def _background_extraction_task(client, user_message, assistant_response):

    # Read the current profile before updating it
    current_long_term = read_long_term()

    prompt = f"""You are a strict long-term memory manager for a caretaker
support chatbot.

Your task is to update the persistent profile using ONLY information that
is explicitly stated by the CARETAKER in the latest interaction.

IMPORTANT MEMORY RULES:

1. NEVER infer or guess facts.
2. NEVER store information that is merely implied.
3. NEVER infer age, gender, diagnosis, relationship, preferences,
   abilities, disabilities, medical conditions, or family structure.
4. Only store a fact if the caretaker explicitly states it.
5. Information provided only by the AI Assistant must NOT become memory.
6. Do not store general advice generated by the assistant as if it were
   something that works for the care recipient.
7. Only store a calming strategy if the caretaker explicitly says that
   the strategy helps, works, is effective, or is currently being used.
8. Do not store casual temporary conversation.
9. Do not store greetings, opinions, questions, or ordinary daily events.
10. Do not duplicate existing facts.
11. If a new fact explicitly updates an existing fact, replace the old fact.
12. Preserve useful existing information that has not changed.
13. NEVER delete useful existing information just because the latest
    interaction does not mention it.

MEMORY CATEGORIES:

### General Info

Use this section ONLY for stable background information about the
care recipient or caretaker.

Examples:
- Age
- Name
- Explicitly stated diagnosis
- Explicit relationship to the caretaker
- Explicit preferences or interests
- Other stable personal information

Example:

Caretaker:
"Emily is 17 years old and she has autism and ADHD."

Store under General Info:
- Emily is 17 years old.
- Emily has autism and ADHD.


### Sensory & Behavioral Triggers

Use this section for sensory sensitivities, fears, behavioral difficulties,
situations that cause distress, anxiety triggers, or situations in which
the care recipient becomes overwhelmed or has difficulty functioning.

Examples:
- Fear of loud noises
- Sensitivity to bright lights
- Difficulty with sudden transitions
- Anxiety in crowded places
- Becoming overwhelmed in noisy environments
- Difficulty handling unexpected changes

Example:

Caretaker:
"Emily gets frightened by sudden loud noises."

Store under Sensory & Behavioral Triggers:
- Emily gets frightened by sudden loud noises.

Example:

Caretaker:
"Emily has difficulty transitioning suddenly between activities."

Store under Sensory & Behavioral Triggers:
- Emily has difficulty transitioning suddenly between activities.


### Calming Strategies & Routines

Use this section ONLY for strategies, activities, routines, or interventions
that the CARETAKER explicitly says help, work, are effective, or are used
to support the care recipient.

Examples:
- Giving advance warnings before transitions
- Watching a favorite program to calm down
- Using a quiet environment
- Listening to calming music
- Following a predictable routine

Example:

Caretaker:
"Giving Emily a 5-minute warning before changing activities helps her
stay calm."

Store under Calming Strategies & Routines:
- Giving Emily a 5-minute warning before changing activities helps her
  stay calm.

IMPORTANT:
Do NOT store a strategy merely because the AI Assistant recommended it.

For example:

Caretaker:
"What can I do when Emily gets overwhelmed?"

Assistant:
"Try giving Emily a weighted blanket."

Do NOT store "weighted blanket" as a successful strategy because the
caretaker has not explicitly said that it works.


CLASSIFICATION RULE:

When a statement contains both a problem/trigger and a successful
strategy, store each piece in the appropriate section.

Example:

Caretaker:
"Emily struggles with sudden transitions, but giving her a 5-minute
warning helps her stay calm."

Store:

### Sensory & Behavioral Triggers
- Emily struggles with sudden transitions.

### Calming Strategies & Routines
- Giving Emily a 5-minute warning before transitions helps her stay calm.


INFERENCE EXAMPLE:

Caretaker:
"Emily probably likes cartoons because she is a child."

Do NOT store that Emily is a child or that she likes cartoons.

The caretaker has expressed an assumption rather than a confirmed fact.


IRRELEVANT INFORMATION EXAMPLE:

Caretaker:
"I had rice and dal for dinner."

Do NOT store this because it is temporary and irrelevant to the
care recipient's long-term profile.


EXISTING PROFILE RULES:

The existing profile is the source of previously stored information.

Preserve all valid existing information.

If new information contradicts an existing fact and the caretaker
explicitly provides the new information, update the old fact.

Example:

Existing:
- Emily is 16 years old.

Caretaker:
"Emily turned 17 last week."

Updated:
- Emily is 17 years old.

Do NOT keep both 16 and 17.

Do NOT create duplicate section headers.

The final profile MUST contain exactly these three sections:

### General Info

### Sensory & Behavioral Triggers

### Calming Strategies & Routines


Existing Long-Term Profile:

{current_long_term}


Latest Interaction:

Caretaker:
{user_message}

Assistant:
{assistant_response}


Return ONLY the complete updated Markdown profile.

Do not include explanations.
Do not include conversational text.
Do not include reasoning.
"""


    try:
        completion = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
        {
            "role": "user",
            "content": prompt
        }
        ],
        temperature=0.0,
        max_completion_tokens=1000,
        reasoning_effort="low",
        include_reasoning=False
    )

        updated_profile = completion.choices[0].message.content.strip()

        # ---------------------------------------------------------
        # SAFETY VALIDATION
        # ---------------------------------------------------------
        # Never overwrite the existing memory with an incomplete
        # or malformed response from the LLM.
        print("\n--- LLM MEMORY OUTPUT ---")
        print(updated_profile)
        print("--- END LLM MEMORY OUTPUT ---\n")
        required_sections = [
            "### General Info",
            "### Sensory & Behavioral Triggers",
            "### Calming Strategies & Routines"
        ]

        profile_is_valid = (
            updated_profile
            and len(updated_profile) > 50
            and all(
                section in updated_profile
                for section in required_sections
            )
        )

        if profile_is_valid:
            write_long_term(updated_profile)
            print("Long-term memory updated successfully.")

        else:
            print(
                "Background extraction returned an invalid profile. "
                "Existing long-term memory was preserved."
            )

    except Exception as e:
        print(f"Background worker extraction error: {e}")


def trigger_background_extraction(
    client,
    user_message,
    assistant_response
):
    t = threading.Thread(
        target=_background_extraction_task,
        args=(
            client,
            user_message,
            assistant_response
        )
    )

    t.daemon = True
    t.start()