import os
import threading

LONG_TERM_FILE = "long_term_memory.md"


def initialize_long_term():
    if not os.path.exists(LONG_TERM_FILE):
        default_content = """# Long-Term User & Caretaker Profile

### General Info
- Caretaker managing a neurodivergent care recipient.

### Sensory & Behavioral Triggers
- None logged yet.

### Calming Strategies & Routines
- None logged yet."""

        with open(LONG_TERM_FILE, "w", encoding="utf-8") as f:
            f.write(default_content)


def read_long_term():
    initialize_long_term()

    with open(LONG_TERM_FILE, "r", encoding="utf-8") as f:
        return f.read()


def write_long_term(content):
    with open(LONG_TERM_FILE, "w", encoding="utf-8") as f:
        f.write(content)


def _background_extraction_task(client, user_message, assistant_response):

    current_long_term = read_long_term()

    prompt = f"""You are a strict long-term memory manager for a caretaker
support chatbot.

Your task is to update the persistent profile using ONLY information that
is explicitly stated by the CARETAKER in the latest interaction.

IMPORTANT RULES:

1. NEVER infer or guess facts.
2. NEVER store information that is merely implied.
3. NEVER infer age, gender, diagnosis, relationship, preferences,
   abilities, disabilities, medical conditions, or family structure.
4. Only store a fact if the caretaker explicitly states it.
5. Information provided only by the AI Assistant must NOT become memory.
6. Do not store general advice generated by the assistant as if it were
   something that works for the care recipient.
7. Only store a calming strategy if the caretaker explicitly says that
   the strategy helps, works, or is used.
8. Do not store casual temporary conversation.
9. Do not store greetings, opinions, questions, or ordinary daily events.
10. Do not duplicate existing facts.
11. If a new fact explicitly updates an existing fact, replace the old fact.
12. Preserve useful existing information that has not changed.

The profile MUST contain exactly these three sections:

### General Info

### Sensory & Behavioral Triggers

### Calming Strategies & Routines

Examples:

Caretaker:
"Emily is 16 years old."

Store:
- Emily is 16 years old.

Caretaker:
"Emily likes Pokémon because it helps her calm down."

Store:
- Emily likes Pokémon.
- Watching Pokémon helps Emily calm down.

Caretaker:
"Emily probably likes cartoons because she is a child."

Do NOT store this because the caretaker is making an inference.

Caretaker:
"What calming strategies can I try?"

Do NOT store the assistant's suggested strategies as facts.

Caretaker:
"I had rice and dal for dinner."

Do NOT store this because it is temporary and irrelevant.

Existing Long-Term Profile:
{current_long_term}

Latest Interaction:

Caretaker:
{user_message}

Assistant:
{assistant_response}

Return ONLY the complete updated Markdown profile.
Do not include explanations.
Do not include conversational text.
"""

    try:
        completion = client.chat.completions.create(
            model="openai/gpt-oss-20b",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.0,
            max_tokens=400
        )

        updated_profile = completion.choices[0].message.content.strip()

        if updated_profile and len(updated_profile) > 20:
            write_long_term(updated_profile)

    except Exception as e:
        print(f"Background worker extraction error: {e}")


def trigger_background_extraction(
    client,
    user_message,
    assistant_response
):
    t = threading.Thread(
        target=_background_extraction_task,
        args=(
            client,
            user_message,
            assistant_response
        )
    )

    t.daemon = True
    t.start()